-- BOOK_LIBRARY DATABASE --

CREATE DATABASE book_library;

-- BOOKS TABLE --

CREATE TABLE books (
    ID INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL UNIQUE,
    authors VARCHAR(200) NOT NULL,
    pages INT NOT NULL,
    PRIMARY KEY (ID)
) DEFAULT CHARSET = utf8;